In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn import cross_validation
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import plot    
import plotly.graph_objs as go
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop
from sklearn.cross_validation import train_test_split
import keras

/home/user/classification/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Using TensorFlow backend.


In [6]:
a=np.arange(16).reshape(4,4)
print(a)
numrows = len(a)    
numcols = len(a[0])
i=0
while(i<numrows):
    j=0
    while(j<numcols):
        maty = np.matrix([[a[i][j],a[i][j+1]], [a[i+1][j],a[i+1][j+1]]])
        print("----")
        print(maty)
        j+=2
    i+=2    
        

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----
[[0 1]
 [4 5]]
----
[[2 3]
 [6 7]]
----
[[ 8  9]
 [12 13]]
----
[[10 11]
 [14 15]]


In [15]:
def max_pool(a,stride):
    #print(a)
    if(stride == 1):
        lists = []
        for k in range(len(a)):
            b = []
            for row in a[k]:
                b.append(row)
            lists.append(np.array(b))
        numrows = len(lists[0])    
        numcols = len(lists[0][0])
        for p in range(len(lists)):
            sums = []
            for i in range(numrows):
                for j in range(numcols):                
                    try:
                        maty = np.matrix([[lists[p][i][j],lists[p][i][j+1]], [lists[p][i+1][j],lists[p][i+1][j+1]]])
                        l = maty.max()
                        sums.append(l)
                    except:
                        continue
            sums1 = np.asarray(sums)
            try:
                B = np.reshape(sums1, (3, 3))
                print(B)
            except:
                continue
    else:
        print("hi")
        lists = []
        for k in range(len(a)):            
            b = []
            for row in a[k]:
                b.append(row)
            lists.append(np.array(b))
        numrows = len(lists[0])    
        numcols = len(lists[0][0])
        for p in range(len(lists)):
            sums = []
            i=0
            while(i<numrows):
                j=0
                while(j<numcols):
                    maty = np.matrix([[lists[p][i][j],lists[p][i][j+1]], [lists[p][i+1][j],lists[p][i+1][j+1]]])
                    #print("----")
                    #print(maty)
                    l = maty.max()
                    sums.append(l)
                    j+=2
                i+=2
                sums1 = np.asarray(sums)
            try:
                B = np.reshape(sums1, (2, 2))
                print(B)
            except:
                continue   

In [17]:
a=np.arange(16).reshape(1,4,4)
#len(a)
#print(a)
max_pool(a,1)

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
